//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class acct : DbContext
    {
        public acct()
            : base("name=acct")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountGroup> AccountGroups { get; set; }
        public virtual DbSet<entry> entries { get; set; }
        public virtual DbSet<entry_items> entry_items { get; set; }
        public virtual DbSet<entry_types> entry_types { get; set; }
        public virtual DbSet<ledger> ledgers { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<setting> settings { get; set; }
    }
}
