//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entry
    {
        public entry()
        {
            this.entry_items = new HashSet<entry_items>();
        }
    
        public int id { get; set; }
        public Nullable<int> tag_id { get; set; }
        public int entry_type { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> dr_total { get; set; }
        public Nullable<decimal> cr_total { get; set; }
        public string narration { get; set; }
    
        public virtual ICollection<entry_items> entry_items { get; set; }
    }
}
