//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class entry_types
    {
        public int id { get; set; }
        public string label { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public int base_type { get; set; }
        public int numbering { get; set; }
        public string prefix { get; set; }
        public string suffix { get; set; }
        public int zero_padding { get; set; }
        public int bank_cash_ledger_restriction { get; set; }
    
        public virtual ledger ledger { get; set; }
    }
}
