//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ledger
    {
        public ledger()
        {
            this.entry_items = new HashSet<entry_items>();
        }
    
        public int id { get; set; }
        public int group_id { get; set; }
        public string name { get; set; }
        public decimal op_balance { get; set; }
        public string op_balance_dc { get; set; }
        public int type { get; set; }
        public bool reconciliation { get; set; }
    
        public virtual AccountGroup AccountGroup { get; set; }
        public virtual ICollection<entry_items> entry_items { get; set; }
        public virtual entry_types entry_types { get; set; }
    }
}
