//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class setting
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> fy_start { get; set; }
        public Nullable<System.DateTime> fy_end { get; set; }
        public string currency_symbol { get; set; }
        public string date_format { get; set; }
        public string timezone { get; set; }
        public Nullable<int> manage_inventory { get; set; }
        public Nullable<int> account_locked { get; set; }
        public string email_protocol { get; set; }
        public string email_host { get; set; }
        public Nullable<int> email_port { get; set; }
        public string email_username { get; set; }
        public string email_password { get; set; }
        public Nullable<double> print_paper_height { get; set; }
        public Nullable<double> print_paper_width { get; set; }
        public Nullable<double> print_margin_top { get; set; }
        public Nullable<double> print_margin_bottom { get; set; }
        public Nullable<double> print_margin_left { get; set; }
        public Nullable<double> print_margin_right { get; set; }
        public string print_orientation { get; set; }
        public string print_page_format { get; set; }
        public Nullable<int> database_version { get; set; }
    }
}
