//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaijaHandyManAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtisanRating
    {
        public int RatingID { get; set; }
        public int UserID { get; set; }
        public int ArtisanID { get; set; }
        public Nullable<decimal> PersonalRating { get; set; }
    
        public virtual Artisan Artisan { get; set; }
        public virtual User User { get; set; }
    }
}
