//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaijaHandyManAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artisan
    {
        public Artisan()
        {
            this.ArtisanRatings = new HashSet<ArtisanRating>();
        }
    
        public int ArtisanID { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Password { get; set; }
        public string OfficialWorkingHours { get; set; }
        public byte[] Picture { get; set; }
        public string CPCRegistrationNumber { get; set; }
        public int JobID { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string FullAddress { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<double> AddressLongitude { get; set; }
        public Nullable<double> AddressLatitude { get; set; }
        public Nullable<double> Rating { get; set; }
        public string Email { get; set; }
        public string JobCore { get; set; }
        public Nullable<int> YearsOfExperience { get; set; }
        public string RegDate { get; set; }
        public Nullable<int> NoOfRecommendations { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual ICollection<ArtisanRating> ArtisanRatings { get; set; }
    }
}
