//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NaijaHandyManAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public Job()
        {
            this.Artisans = new HashSet<Artisan>();
        }
    
        public int JobID { get; set; }
        public string JobType { get; set; }
    
        public virtual ICollection<Artisan> Artisans { get; set; }
    }
}
